---

- name: Deploy to server
  hosts: servers
  user: adam

  tasks:
    - name: Clone repo
      git: repo={{ repo_url }} dest=/var/www/{{host}}
    - name: Install nginx config
      template: src=nginx.j2 dest=/etc/nginx/sites-available/cyanoryx
      sudo: yes
    - name: Enable nginx config
      file: src=/etc/nginx/sites-available/cyanoryx dest=/etc/nginx/sites-enabled/cyanoryx state=link
      sudo: yes
      notify:
        - restart nginx
